// Common HTML tags with descriptions
export const HTML_TAGS = [
    { tag: 'div', description: 'Generic container element' },
    { tag: 'span', description: 'Inline container element' },
    { tag: 'p', description: 'Paragraph' },
    { tag: 'a', description: 'Hyperlink' },
    { tag: 'img', description: 'Image', selfClosing: true },
    { tag: 'h1', description: 'Heading level 1' },
    { tag: 'h2', description: 'Heading level 2' },
    { tag: 'h3', description: 'Heading level 3' },
    { tag: 'h4', description: 'Heading level 4' },
    { tag: 'h5', description: 'Heading level 5' },
    { tag: 'h6', description: 'Heading level 6' },
    { tag: 'ul', description: 'Unordered list' },
    { tag: 'ol', description: 'Ordered list' },
    { tag: 'li', description: 'List item' },
    { tag: 'table', description: 'Table' },
    { tag: 'tr', description: 'Table row' },
    { tag: 'td', description: 'Table data cell' },
    { tag: 'th', description: 'Table header cell' },
    { tag: 'thead', description: 'Table header group' },
    { tag: 'tbody', description: 'Table body group' },
    { tag: 'tfoot', description: 'Table footer group' },
    { tag: 'form', description: 'Form element' },
    { tag: 'input', description: 'Input field', selfClosing: true },
    { tag: 'textarea', description: 'Multi-line text input' },
    { tag: 'button', description: 'Button element' },
    { tag: 'select', description: 'Dropdown select' },
    { tag: 'option', description: 'Option in select' },
    { tag: 'label', description: 'Label for form element' },
    { tag: 'header', description: 'Header section' },
    { tag: 'footer', description: 'Footer section' },
    { tag: 'nav', description: 'Navigation section' },
    { tag: 'main', description: 'Main content' },
    { tag: 'section', description: 'Section of content' },
    { tag: 'article', description: 'Article content' },
    { tag: 'aside', description: 'Sidebar content' },
    { tag: 'br', description: 'Line break', selfClosing: true },
    { tag: 'hr', description: 'Horizontal rule', selfClosing: true },
    { tag: 'strong', description: 'Strong emphasis (bold)' },
    { tag: 'em', description: 'Emphasis (italic)' },
    { tag: 'b', description: 'Bold text' },
    { tag: 'i', description: 'Italic text' },
    { tag: 'u', description: 'Underlined text' },
    { tag: 'small', description: 'Smaller text' },
    { tag: 'code', description: 'Code snippet' },
    { tag: 'pre', description: 'Preformatted text' },
    { tag: 'blockquote', description: 'Block quotation' },
    { tag: 'script', description: 'JavaScript code' },
    { tag: 'style', description: 'CSS styles' },
    { tag: 'link', description: 'External resource link', selfClosing: true },
    { tag: 'meta', description: 'Metadata', selfClosing: true },
    { tag: 'title', description: 'Document title' },
    { tag: 'head', description: 'Document head' },
    { tag: 'body', description: 'Document body' },
    { tag: 'html', description: 'HTML root element' },
    { tag: 'iframe', description: 'Inline frame' },
    { tag: 'canvas', description: 'Canvas for graphics' },
    { tag: 'svg', description: 'Scalable vector graphics' },
    { tag: 'video', description: 'Video player' },
    { tag: 'audio', description: 'Audio player' },
    { tag: 'source', description: 'Media source', selfClosing: true },
];

// Check if a tag is self-closing
export function isSelfClosingTag(tagName: string): boolean {
    const tag = HTML_TAGS.find(t => t.tag.toLowerCase() === tagName.toLowerCase());
    return tag?.selfClosing === true;
}